### ISSUE TITLE
issues for solve

### ISSUE THREAD

**Issue by johnfelipe** [ethanshealey/translator#1]
root@felipe:~# git clone https://github.com/ethanshealey/translator.git
	Cloning into 'translator'...
	remote: Enumerating objects: 2970, done.
	remote: Counting objects: 100% (2970/2970), done.
	remote: Compressing objects: 100% (2160/2160), done.
	remote: Total 2970 (delta 707), reused 2962 (delta 699), pack-reused 0
	Receiving objects: 100% (2970/2970), 4.66 MiB | 2.06 MiB/s, done.
	Resolving deltas: 100% (707/707), done.
	root@felipe:~# cd translator/
	root@felipe:~/translator# cd server/
	root@felipe:~/translator/server# npm install

	up to date, audited 181 packages in 917ms

	13 packages are looking for funding
	  run `npm fund` for details

	found 0 vulnerabilities
	root@felipe:~/translator/server# cd ..
	root@felipe:~/translator# cd client/
	root@felipe:~/translator/client# npm install
	npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
	npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

	added 1478 packages, and audited 1679 packages in 46s

	190 packages are looking for funding
	  run `npm fund` for details

	7 vulnerabilities (1 moderate, 6 high)

	To address issues that do not require attention, run:
	  npm audit fix

	To address all issues (including breaking changes), run:
	  npm audit fix --force

	Run `npm audit` for details.
	root@felipe:~/translator/client# cd ..
	root@felipe:~/translator# cd server/
	root@felipe:~/translator/server# npm start

	> server@1.0.0 start
	> node index.js

	Listening on 3000
	Error: Missing required parameters: apikey
		at Object.getMissingParams (/root/translator/server/node_modules/ibm-cloud-sdk-core/lib/helper.js:119:11)
		at Object.validateInput (/root/translator/server/node_modules/ibm-cloud-sdk-core/auth/utils/helpers.js:64:39)
		at new IamAuthenticator (/root/translator/server/node_modules/ibm-cloud-sdk-core/auth/authenticators/iam-authenticator.js:70:17)
		at getTranslatorInstance (/root/translator/server/index.js:18:20)
		at /root/translator/server/index.js:31:17
		at Layer.handle [as handle_request] (/root/translator/server/node_modules/express/lib/router/layer.js:95:5)
		at next (/root/translator/server/node_modules/express/lib/router/route.js:144:13)
		at Route.dispatch (/root/translator/server/node_modules/express/lib/router/route.js:114:3)
		at Layer.handle [as handle_request] (/root/translator/server/node_modules/express/lib/router/layer.js:95:5)
		at /root/translator/server/node_modules/express/lib/router/index.js:284:15

and client

	Compiled with warnings.

	Failed to parse source map: 'webpack://antd/./components/config-provider/style/index.less' URL is not supported

	Failed to parse source map: 'webpack://antd/./components/icon/style/index.less' URL is not supported

	Failed to parse source map: 'webpack://antd/./components/locale-provider/style/index.less' URL is not supported

	Failed to parse source map: 'webpack://antd/./components/time-picker/style/index.less' URL is not supported

	Search for the keywords to learn more about each warning.
	To ignore, add // eslint-disable-next-line to the line before.

	WARNING in ./node_modules/antd/dist/antd.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/antd/dist/antd.css)
	Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
	Failed to parse source map: 'webpack://antd/./components/config-provider/style/index.less' URL is not supported

	WARNING in ./node_modules/antd/dist/antd.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/antd/dist/antd.css)
	Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
	Failed to parse source map: 'webpack://antd/./components/icon/style/index.less' URL is not supported

	WARNING in ./node_modules/antd/dist/antd.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/antd/dist/antd.css)
	Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
	Failed to parse source map: 'webpack://antd/./components/locale-provider/style/index.less' URL is not supported

	WARNING in ./node_modules/antd/dist/antd.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/antd/dist/antd.css)
	Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
	Failed to parse source map: 'webpack://antd/./components/time-picker/style/index.less' URL is not supported

	webpack compiled with 4 warnings

![SNAG-1188](https://user-images.githubusercontent.com/428820/172034066-891e7279-f77b-448c-9405-6a864e0bd7e2.png)

**Comment by ethanshealey** [comment]
You need to get your own API key from IBM: https://cloud.ibm.com/apidocs/language-translator

It is stored in `.env` under the name `API_KEY`

Your `.env` file should look like
`API_KEY=xxxxxxxxxxxxxxxxxxxxxxx`
